/*
  Copyright (C) Skeletex Research, s.r.o. - All Rights Reserved
  Unauthorized copying of this file, via any medium is strictly prohibited
  Proprietary and confidential
*/
#ifndef GLW_UTILS_H
#define GLW_UTILS_H
#include <string>
#include <utility>
#include <GLW/API.h>
#include <Utils/Version.h>

namespace glw
{

  //! Returns true when OpenGL was initialized.
  GLW_API bool IsOpenGLInitialized();

  //! Returns all errors generated by OpenGL since last time this function was called.
  GLW_API std::string GetError();

  // Returns GL_VENDOR as std::string.
  GLW_API std::string GetOpenGlVendor();

  // Returns GL_RENDERER as std::string.
  GLW_API std::string GetOpenGlRenderer();

  // Returns GL_VERSION as std::string.
  GLW_API std::string GetOpenGlVersion();

  //! Get OpenGL version actually active on system.
  GLW_API utils::Version GetCurrentOpenGlVersion();

}

#endif /* !GLW_UTILS_H */